In [4]:
import numpy as np
def addmatrices(A,B):
  return np.add(A,B)
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print("Matrix A:\n",A)
print("Matrix B:\n",B)
print("Addition of 2 matrices A and B:\n",addmatrices(A,B))

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Addition of 2 matrices A and B:
 [[ 6  8]
 [10 12]]
